#!/usr/bin/env python3
"""Generate a synthetic ResMed-style SD-card dataset for demos and CI.

Builds <out>/DATALOG/<YYYYMMDD>/{<ts>_BRP,_PLD,_SAD,_EVE}.edf plus a
tuning_log.json with two prescription segments. Fully deterministic (fixed
seed). The nights are archetyped to exercise every analysis path:

  quiet / flow-limited / clustered / moderate      normal analysable nights
  CSR-like                                          full-night periodic breathing
  short+leaky                                       fails the quality gates (* row)

Usage:
  python examples/generate_demo_data.py                 # → examples/demo/data
  python examples/generate_demo_data.py /tmp/mydata     # custom target
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, time, timedelta
from pathlib import Path

import numpy as np
from edfio import Edf, EdfAnnotation, EdfSignal, Recording

FS_BRP = 25.0   # flow + pressure
FS_PLD = 0.5    # summary channels
FS_SAD = 1.0    # SpO2 + pulse rate

# nightly archetypes: (label, hours, base-pressure bias, OA, HYP, CA counts,
#                      clustered?, periodic?, leaky?, flow-limitation factor)
NIGHTS = [
    ("quiet",        6.6, 0.0,  2, 1, 0, False, False, False, 0.6),
    ("flow-limited", 6.4, -0.8, 6, 2, 0, False, False, False, 1.0),
    ("clustered",    6.8, 0.2,  9, 2, 0, True,  False, False, 0.5),
    ("moderate",     6.5, 0.0,  4, 2, 0, False, False, False, 0.5),
    ("quiet",        6.7, 0.0,  1, 0, 0, False, False, False, 0.4),
    ("clustered+late", 6.9, 0.3, 8, 3, 0, True,  False, False, 0.5),
    ("csr-like",     6.6, 0.0,  0, 4, 5, False, True,  False, 0.3),
    ("moderate",     6.5, 0.1,  5, 2, 1, False, False, False, 0.5),
    ("short+leaky",  1.6, 0.0,  1, 0, 0, False, False, True,  0.4),
    ("late-heavy",   6.8, 0.0,  6, 1, 0, False, False, False, 0.5),
]

# segment boundary: nights 1-4 on the initial settings, 5+ after the floor raise
SEG2_SINCE = "20240305"

TUNING_LOG = {
    "device": "ResMed AirSense 10 AutoSet (synthetic demo)",
    "mask": "nasal",
    "note": "Synthetic tuning log generated by generate_demo_data.py",
    "log": [
        {"since": "20240301", "label": "initial 9-14 EPR1",
         "min_press": 9, "max_press": 14, "epr": 1,
         "note": "demo segment A"},
        {"since": SEG2_SINCE, "label": "floor 10-15 EPR1",
         "min_press": 10, "max_press": 15, "epr": 1,
         "note": "demo segment B (floor raised)"},
    ],
}


def _night_date(i: int) -> str:
    return (date(2024, 3, 1) + timedelta(days=i)).strftime("%Y%m%d")


def build_pressure(t_s, rng, min_press, max_press, night, events):
    """Ramp → wandering base → reactive post-event bumps, clipped at the ceiling.

    The reactive bumps emulate AutoSet behaviour (event -> +Δ over ~2 min, slow
    decay), which the feedback check in --wave is designed to detect.
    """
    ramp_s = 45 * 60
    base = min_press + 2.0 + 0.6 * np.sin(2 * np.pi * t_s / 5400.0) \
        + 0.25 * np.sin(2 * np.pi * t_s / 1300.0)
    ramp = np.clip(t_s / ramp_s, 0, 1) ** 0.7
    p = 4.5 + (base - 4.5) * ramp
    bump_amp = 1.2 if night[0] == "late-heavy" else 0.7
    for kind, onset in events:
        if kind != "oa":
            continue
        rise = bump_amp * np.clip((t_s - onset) / 120.0, 0, 1)          # +Δ over 2 min
        decay = np.exp(-np.clip(t_s - onset - 120.0, 0, None) / 600.0)  # ~10 min decay
        p = p + rise * decay
    noise = rng.normal(0, 0.04, t_s.size)
    return np.clip(p + noise, 4.0, max_press)


def build_flow(t_s, fs, rng, press, night, events, limitation):
    """Asymmetric synthetic breathing; plateau-shaped inspiration where pressure
    is low (flow limitation), near-zero flow during events, optional periodic
    tidal-volume modulation (CSR-like nights)."""
    rr0 = 13.2 / 60.0
    phase_jitter = np.cumsum(rng.normal(0, 0.0015, t_s.size)) / fs
    phase = 2 * np.pi * rr0 * (t_s + phase_jitter)
    insp = np.sin(phase) ** 3                       # rounded, slightly asymmetric
    # pressure deficit → limitation (0..1): FI drops when pressure is low
    p_ref = np.median(press)
    deficit = np.clip((p_ref - 0.4 - press) / 2.2, 0, 1) * limitation
    limited = deficit > 0.05
    plateau = np.sign(insp) * np.abs(insp) ** 0.12
    shape = np.where(limited, plateau, insp)
    amp = 0.34 * (1 + 0.08 * np.sin(2 * np.pi * t_s / 900.0))
    if night[6]:  # periodic breathing: tidal-volume modulation, 46 s period
        amp = amp * (1 + 0.55 * np.sin(2 * np.pi * t_s / 46.0))
    flow = amp * shape + rng.normal(0, 0.012, t_s.size)
    # events flatten the flow
    for kind, onset in events:
        dur = {"oa": 24.0, "ca": 20.0, "hyp": 18.0}[kind]
        m = (t_s >= onset) & (t_s < onset + dur)
        depth = 0.02 if kind in ("oa", "ca") else 0.45
        flow[m] = flow[m] * depth + rng.normal(0, 0.008, int(m.sum()))
    return flow


def _place_events(rng, n_oa, n_hyp, n_ca, clustered, hours, late_bias):
    """Event onset list; clustered nights get 2 dense bursts, late-biased nights
    push half the events into the final third."""
    total = n_oa + n_hyp + n_ca
    span = hours * 3600 - 600
    evs = []
    if clustered:
        for c0 in (span * 0.33, span * 0.62):
            evs += [("oa", c0), ("oa", c0 + 75), ("oa", c0 + 150), ("oa", c0 + 210)]
        n_oa -= 8
    for i in range(max(n_oa, 0)):
        u = rng.uniform(0.05, 0.95)
        if late_bias:
            u = 0.35 + 0.6 * u
        evs.append(("oa", span * u))
    for i in range(n_hyp):
        evs.append(("hyp", span * rng.uniform(0.05, 0.95)))
    for i in range(n_ca):
        evs.append(("ca", span * rng.uniform(0.05, 0.95)))
    return sorted(set(evs), key=lambda e: e[1])[: max(total, 1)] or [("oa", span / 2)]


def write_night(out_root: Path, idx: int, seed: int):
    night = NIGHTS[idx]
    label, hours, pbias, n_oa, n_hyp, n_ca, clustered, periodic, leaky, lim = night
    rng = np.random.default_rng(seed + idx * 100)
    night_dir = _night_date(idx)
    seg = TUNING_LOG["log"][0] if night_dir < SEG2_SINCE else TUNING_LOG["log"][1]
    min_press, max_press = seg["min_press"], seg["max_press"]

    dur_s = hours * 3600
    t_brp = np.arange(0, dur_s, 1.0 / FS_BRP)
    events = _place_events(rng, n_oa, n_hyp, n_ca, clustered, hours, label == "late-heavy")

    press = build_pressure(t_brp, rng, min_press + pbias, max_press, night, events)
    flow = build_flow(t_brp, FS_BRP, rng, press, night, events, lim)

    hh, mm = (22, 5 + (idx * 7) % 40) if not leaky else (23, 30)
    stamp = f"{hh:02d}{mm:02d}{17:02d}"
    base = out_root / night_dir
    base.mkdir(parents=True, exist_ok=True)

    def _edf(path, signals, annotations=None):
        e = Edf(signals=signals, starttime=time(hh, mm, 17),
                recording=Recording(startdate=date(int(night_dir[:4]), int(night_dir[4:6]), int(night_dir[6:]))),
                annotations=annotations or [])
        e.write(path)

    def sig(data, fs, name, lo, hi):
        return EdfSignal(np.asarray(data, dtype=np.float64), sampling_frequency=fs,
                         label=name, physical_range=(lo, hi))

    _edf(base / f"{stamp}_BRP.edf",
         [sig(flow, FS_BRP, "Flow", -3.0, 3.0), sig(press, FS_BRP, "Press", 4.0, 20.0)])

    # PLD at 0.5 Hz: downsample pressure; derive the summaries from the model
    step = int(FS_BRP / FS_PLD)
    p05 = press[::step]
    t05 = t_brp[::step]
    deficit = np.clip((np.median(press) - 0.4 - p05) / 2.2, 0, 1) * lim
    leak_base = 26.0 if leaky else 6.0
    leak = leak_base + 2.0 * np.sin(2 * np.pi * t05 / 3000.0) + rng.normal(0, 1.2, t05.size)
    if leaky:
        leak += 6.0 * (np.sin(2 * np.pi * t05 / 700.0) > 0.6)
    leak = np.clip(leak, 0.5, None)
    rr = 13.2 + 0.5 * np.sin(2 * np.pi * t05 / 2500.0) + rng.normal(0, 0.15, t05.size)
    tv = 0.46 * (1 - 0.30 * deficit) * (1 + (0.55 * np.sin(2 * np.pi * t05 / 46.0) if periodic else 0.0)) \
        + rng.normal(0, 0.008, t05.size)
    mv = rr * tv + rng.normal(0, 0.05, t05.size)   # L/min = breaths/min × L
    snore = 0.02 + rng.normal(0, 0.005, t05.size)
    for kind, onset in events:
        if kind == "oa":
            m = (t05 > onset - 40) & (t05 < onset)
            snore[m] += 0.35
    snore = np.clip(snore, 0.0, None)
    flowlim = np.clip(0.28 * deficit + rng.normal(0, 0.01, t05.size), 0, 1)

    _edf(base / f"{stamp}_PLD.edf",
         [sig(p05, FS_PLD, "Press", 4.0, 20.0), sig(leak, FS_PLD, "Leak", 0.0, 40.0),
          sig(rr, FS_PLD, "RespRate", 8.0, 30.0), sig(tv, FS_PLD, "TidVol", 0.1, 1.2),
          sig(mv, FS_PLD, "MinVent", 2.0, 15.0), sig(snore, FS_PLD, "Snore", 0.0, 1.5),
          sig(flowlim, FS_PLD, "FlowLim", 0.0, 1.0)])

    # SAD: SpO2 with post-cluster dips + pulse rate
    t01 = np.arange(0, dur_s, 1.0 / FS_SAD)
    spo2 = 96.0 + 0.6 * np.sin(2 * np.pi * t01 / 4200.0) + rng.normal(0, 0.25, t01.size)
    for kind, onset in events:
        if kind == "oa":
            m = (t01 > onset + 20) & (t01 < onset + 140)
            spo2[m] -= 5.5
    spo2 = np.clip(spo2, 84, 99)
    pr = 62 + 6 * np.sin(2 * np.pi * t01 / 3600.0) + rng.normal(0, 1.2, t01.size)
    _edf(base / f"{stamp}_SAD.edf",
         [sig(spo2, FS_SAD, "SpO2", 50.0, 100.0), sig(pr, FS_SAD, "PR", 40.0, 120.0)])

    # EVE: event annotations (onsets relative to recording start)
    label_map = {"oa": "Obstructive Apnea", "ca": "Central Apnea", "hyp": "Hypopnea"}
    annots = [EdfAnnotation(float(onset), {"oa": 24.0, "ca": 20.0, "hyp": 18.0}[kind], label_map[kind])
              for kind, onset in events]
    dummy = sig(np.zeros(1, dtype=np.float64), 1.0 / dur_s, "Events", -1.0, 1.0)
    _edf(base / f"{stamp}_EVE.edf", [dummy], annots)
    return night_dir, len(events)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("out", nargs="?", default=str(Path(__file__).resolve().parent / "demo" / "data"),
                    help="target data directory (default: examples/demo/data)")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args(argv)

    out = Path(args.out)
    datalog = out / "DATALOG"
    datalog.mkdir(parents=True, exist_ok=True)
    n_events = 0
    for i in range(len(NIGHTS)):
        d, k = write_night(datalog, i, args.seed)
        n_events += k
        print(f"  {d}: {NIGHTS[i][0]:<14} {NIGHTS[i][1]:>4.1f} h, {k} events")
    (out / "tuning_log.json").write_text(json.dumps(TUNING_LOG, indent=2), encoding="utf-8")
    print(f"\n{len(NIGHTS)} synthetic nights ({n_events} events) → {out}")
    print("next: RSDM_DATA_DIR=<out> resmed-sd-monitor --report   (or --data-dir <out>)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
